name 'munge'
maintainer 'David Brown'
maintainer_email 'dmlb2000@gmail.com'
license 'all_rights'
description 'Installs/Configures munge'
long_description 'Installs/Configures munge'
issues_url 'https://github.com/dmlb2000/munge-cookbook/issues'
source_url 'https://github.com/dmlb2000/munge-cookbook'
version '0.1.0'

depends 'yum-epel'
